version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s | %(levelname)8s | %(name)s | %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: log.log
    mode: a

root:
  level: DEBUG
  handlers: [console, file]

loggers:
  urllib3:
    level: WARN
    # propagate: False

